{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fftrees
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FFTrees_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FFTrees/FFTrees_{{ version }}.tar.gz
  sha256: b4c8588696518bc3533a22a39ee47c88f56af6f7a636572b4b5bff2de02acd92

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-caret
    - r-cli
    - r-dplyr
    - r-e1071
    - r-knitr
    - r-magrittr
    - r-progress
    - r-randomforest
    - r-rpart
    - r-scales
    - r-stringr
    - r-testthat
    - r-tibble
    - r-tidyselect
    - r-knitr
  run:
    - r-base
    - r-caret
    - r-cli
    - r-dplyr
    - r-e1071
    - r-knitr
    - r-magrittr
    - r-progress
    - r-randomforest
    - r-rpart
    - r-scales
    - r-stringr
    - r-testthat
    - r-tibble
    - r-tidyselect
    - r-knitr

test:
  commands:
    - $R -e "library('FFTrees')"           # [not win]
    - "\"%R%\" -e \"library('FFTrees')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=FFTrees
  license: CC0-1.0
  summary: Create, visualize, and test fast-and-frugal decision trees (FFTs). FFTs are very simple decision trees for binary classification problems. FFTs can be preferable to more complex algorithms because they are easy to communicate, require very little information, and are robust against overfitting.
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
