{% set version = "1.7.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fftrees
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FFTrees_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FFTrees/FFTrees_{{ version }}.tar.gz
  sha256: 8390c5edd9ffe138d410f014c9c6b3b64090d1c415479538fd74eb6c4b46112b

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-caret
    - r-circlize
    - r-e1071
    - r-igraph
    - r-proc
    - r-progress
    - r-randomforest
    - r-rpart
    - r-stringr
    - r-yarrr
    - r-knitr
  run:
    - r-base
    - r-caret
    - r-circlize
    - r-e1071
    - r-igraph
    - r-proc
    - r-progress
    - r-randomforest
    - r-rpart
    - r-stringr
    - r-yarrr
    - r-knitr

test:
  commands:
    - $R -e "library('FFTrees')"           # [not win]
    - "\"%R%\" -e \"library('FFTrees')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=FFTrees
  license: CC0-1.0
  summary: Create, visualize, and test fast-and-frugal decision trees (FFTs). FFTs are very simple decision trees for binary classification problems. FFTs can be preferable to more complex algorithms because they are easy to communicate, require very little information, and are robust against overfitting.
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
