{% set version = "2.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fftrees
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FFTrees_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FFTrees/FFTrees_{{ version }}.tar.gz
  sha256: d48d7f0c7c7a6ea0c89eca1ba785bbb2be2ab12337d5cc798d67f34f16db4f17

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-caret
    - r-cli
    - r-dplyr
    - r-e1071
    - r-knitr
    - r-magrittr
    - r-progress
    - r-randomforest
    - r-rpart
    - r-scales
    - r-stringr
    - r-testthat
    - r-tibble
    - r-tidyselect
    - r-knitr
  run:
    - r-base
    - r-caret
    - r-cli
    - r-dplyr
    - r-e1071
    - r-knitr
    - r-magrittr
    - r-progress
    - r-randomforest
    - r-rpart
    - r-scales
    - r-stringr
    - r-testthat
    - r-tibble
    - r-tidyselect
    - r-knitr

test:
  commands:
    - $R -e "library('FFTrees')"           # [not win]
    - "\"%R%\" -e \"library('FFTrees')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=FFTrees
  license: CC0-1.0
  license_file: LICENSE
  summary: Create, visualize, and test fast-and-frugal decision trees (FFTs). FFTs are very simple decision trees for binary classification problems. FFTs can be preferable to more complex algorithms because they are easy to communicate, require very little information, and are robust against overfitting.

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
