appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: mTzXyELXwzmDjJRVMu4z3P3C2DcKMwPlFjEzhkkGAjHhx9RCcUPksANCtlDxtUVHbBIq4DlvSk9l1dTcooPitFo6jvAN8vA0snZTU9ywIdx1izrH7Z+z62IlMM979c0PPC59vYVVBKosb9f0WWVYEWuteqFrliAYfTEgRgHY0/RuPdXN6NN6p0CDzANTss4mLzHX4LooIj2F60bwkolHyHiPvwMptXWgvU9hLgK4cK8KjA5IP96oi+DqsPniHvy0313ro9QbjfrljeYUxkCQo01OHIdqGSCdgkwyonn/UlMIDjcwuHd5/NjLwh257qdoMKBv1bPt9q1WJIIC1yRBCeIB0s+W9NTNCWR8akvP2RNMosUz65PBJLUsfdOLW6cCJQQXRMzqk7F+Y8kxhw9dt7+4+d4x/eKD4NH0HOmy3adetAMq9yXbMI2V35aUD4b8C0oOxN3CGYnGrFFFS3VDEqWDUucA99yIqEi2n6GgOWvr/ZpTmUN1FQr14HpPOf9js0UypQgHFovZZ3aIVd3/Um1nHY6EKDUHlVjPnsgK9MpBXcbLexQKJkWoLePSTL4Lhps6sgZUxia5gDyRTTulFv10sreoSosVSgS1RvhXSoqAB01gO0TeFfOCTzBd0CX6LSqUeKTLoQsUIL04zL+ye4yfMDFvhkzOD9fPSKExCAQ=
